# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db601e44fb78d90a0cc91db7107c16469bc57a3d8ce437940366cba8ac327386eef4fc682f2cf4d667abf0d25ff0fc0d80ffc4f6a224b8d032a67dc850a9b6b2

test:
  secret_key_base: 1a7c8f7b83be857742f5a79d39046c63793d52387f0aa40894a4c52d443058c9926c7e644266cf920182b2f4137bb8f07376ba8938d4e9ede90e4e3ef59c5d59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
